### ISSUE TITLE
Generation of the SIRI classes

### ISSUE THREAD

**Issue by pmiddend** [laidig/siri-20-java#1]
Hi,

I was wondering how you generated the SIRI classes. I tried it with JAXB, but had some issues with conflicting element names. Did you use xjc? If so, how did you invoke it? Could you maybe commit the generation XML/script/whatever into the repository?

**Comment by laidig** [comment]
First, thanks for your question! It's good to see that someone has used this. 

I used xjc to compile (no extensions or format overrides, which might not be optimal in case of java timestamps), it has worked on Java6-8 on both OS X and Windows. 

$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

$ xjc -version
xjc 2.2.8-b130911.1802

$ xjc siriSg.xsd
parsing a schema...
compiling a schema...
eu/datex2/schema/_2_0rc1/_2_0/AbnormalTraffic.java
...

**Comment by pmiddend** [comment]
Sorry for not replying. Thank you for the command line! I had some troubles with some of the types (notably the ones defined ifopt/ which collide with the siri types). But I now managed to resolve them using rewrite rules in the bindings file.
